# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:            Tommy's Blog
tagline:          'Experiences, Discoveries, and occasional opinions of a software engineer'
email:            tommy@gmetrix.com
description: >- 
  A Blog of Experiences, Discoveries, and occasional opinions of a software engineer.
baseurl:          "https://simpert.github.io/" # the subpath of your site, e.g. /blog
url:              "https://simpert.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tommysimper
github_username:  simpert

# Build settings
markdown: kramdown
#theme: minima
#plugins:
#  - jekyll-feed

paginate:  3

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

highlighter: pygments

# Dependencies
#markdown:         redcarpet

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Custom vars
version:          2.1.0

author:
  name:           'Tommy Simper'
  url:            https://twitter.com/TommySimper

github:
  repo:           https://github.com/simpert/simpert.github.com/

