#markdown:         'redcarpet'
highlighter:      'pygments'

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Tommy's Blog
tagline:          'Experiences, Discoveries, and occasional opinions of a software engineer'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://simpert.github.io
baseurl:          /

author:
  name:           'Tommy Simper'
  url:            https://twitter.com/TommySimper

paginate:         5

# Custom vars
version:          2.1.0

github:           'https://github.com/simpert'
  repo:           'simpert.github.com'

#twitter_username: tommysimper
#github_username:  simpert
#email: tommy@gmetrix.com