# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title:            Tommy Simper's Blog
tagline:          'Software Engineer @ <a href="http://www.gmetrix.com">GMetrix</a>'
email:            tommy@gmetrix.com
description:      'A Blog of Experiences, Discoveries, and Occasional Opinions of a Software Engineer.'
baseurl:          '/'
url:              'https://simpert.github.io'
twitter_username: tommysimper
github_username:  simpert

# Build settings
markdown:         kramdown
paginate:         3
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Custom vars
version:          1.0.3

author:
  name:           'Tommy Simper'
  url:            https://twitter.com/TommySimper

#github:
#  repo:           https://github.com/simpert/simpert.github.com/

