
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true


title: Tommy's Blog
tagline:          'Experiences, Discoveries, and occasional opinions of a software engineer'
email: tommy@gmetrix.com
description: >- # this means to ignore newlines until "baseurl:"
  Experiences, Discoveries, and occasional opinions of a software engineer
baseurl: "/" # the subpath of your site, e.g. /blog
author: "Tommy Simper"

url: "https://simpert.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: tommysimper
github_username:  simpert
github:
  repo:           "https://simpert.github.io"
paginate:         5

# Custom vars
version:          2.1.0

# Build settings
#markdown: kramdown
#theme: minima
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/